### ISSUE TITLE
Statistics on front page doesn't work

### ISSUE THREAD

**Issue by Maijin** [hteso/iaito#76] opened 2017-04-04 10:09 UTC
![image](https://cloud.githubusercontent.com/assets/1408600/24651812/7f59b22a-192f-11e7-8bfa-6f5d88de983d.png)

**Comment by hteso** [comment] 2017-04-04 10:30
Indeed, it fails sometimes. I haven't been able to reproduce the cause, it can't be random but I can't find the cause.

**Comment by ballessay** [comment] 2017-04-11 20:39
I experienced this issue, too. When the graphs are not visible the web inspector showed an empty `Chart.js ` here. I played around a bit and the problem seems to be timing related. If the window gets displayed early (window frame already visible without content; short analyze) the graphs are not displayed. If it takes a while to display it works. Strangely if I use `qrc:///` as scheme it always seems to work. So possible solutions:
1. Use `qrc:///` in html files
2. Set the `baseUrl` parameter of `QWebView::setHtml()` to `QUrl("qrc:///")` and remove `qrc:/` from the script paths in the html files

@hteso can try if this fixes it for you too?

**Comment by hteso** [comment] 2017-04-12 11:00
Thanks for the extensive testing and fixes, I'll try as soon as I have a moment. Feel free to submit a PR though if you want :)

**Comment by ballessay** [comment] 2017-04-12 11:39
@hteso I can submit a PR this evening. Would be nice to know if this fixes the behavior for you too. What would be your preferred solution?

**Comment by ballessay** [comment] 2017-04-12 17:44
Seems to work fine now with the change to `QWebEngineView` from  eae419ef3b2177cb1d50a1fea474b0bfeafce32e

**Comment by hteso** [comment] 2017-04-12 18:06
Let's try for a few days and close the issue if it doesn't happen again :)

**Comment by Maijin** [comment] 2017-04-12 18:51
I tested several binaries seems to work fine

**Closed** 2017-05-06 14:01 UTC
