### ISSUE TITLE
Graph view starts with almost all boxes overlapping

### ISSUE THREAD

**Issue by DigiAngel** [hteso/iaito#52] opened 2017-04-01 18:15 UTC
Screenshot :)
![screenshot from 2017-04-01 12-05-04](https://cloud.githubusercontent.com/assets/947191/24581237/e12b2a9a-16d4-11e7-86d4-b6bc007d905d.png)

**Comment by hteso** [comment] 2017-04-02 10:27
Yes, known issue that had no issue :) Thanks for creating it. I'll assign to the graph view developer.

**Comment by DigiAngel** [comment] 2017-04-02 12:11
Ok cool..thank you!

**Comment by trufae** [comment] 2017-04-03 08:36
i cant get the graphs to work at all they are always empty

**Comment by hteso** [comment] 2017-04-03 09:06
http por was changed to "13140" but, for some reason, now r2 is not changing it and starts the web server in the default 9090. That's why the graphs doesn't work. I'll go back to the 9090 as a quick fix.

**Comment by trufae** [comment] 2017-04-03 09:14
who changed that port? because thats not a change in core

**Comment by hteso** [comment] 2017-04-03 09:14
Changing the port back to 9090 doesn't fix the issue. I'll keep looking.

**Comment by trufae** [comment] 2017-04-03 09:29
we need a way to specify a random port and feedback that to iaito, i have a bunch of ideas to solve that using bind to 0 or trying incremental ports, need to test on different OSses and approecahes, to avoid problems, but that should be ready for 1.4

**Comment by pwntester** [comment] 2017-04-03 12:42
For the graph not working at all problem, it seems like r2 returns `No functions to diff` when executing `agj <offset>` although `aa` is executed before. Any changes in r2 that may have affected `agj`?

Running `agj` from iaito interactive console works though ...

**Comment by trufae** [comment] 2017-04-03 13:44
wat

**Comment by pwntester** [comment] 2017-04-03 14:27
`r2.cmd("iSj", function(x) {console.log(x)})` returns `[]`
It seems like if iaito were connected to another r2 instance which has not even loaded the binary.
May be related with: https://github.com/hteso/iaito/commit/0317cf2663fcf0942100030c52dbb2c506bb2f27

**Comment by pwntester** [comment] 2017-04-03 21:43
ok, back to the original issue, I cant reproduce the overlapped boxes. @DigiAngel, Can you provide steps to reproduce?

**Comment by DigiAngel** [comment] 2017-04-03 22:37
I sure will...gimme like 45 minutes.

**Comment by DigiAngel** [comment] 2017-04-03 23:35
Well crazytown...I can't replicate it now either....everything I throw at it works great so eh...if it happens again I'll try and get it to where it's reproducible before I report...sorry about the noise.

**Comment by pwntester** [comment] 2017-04-03 23:39
no problem, closing for now

**Closed by pwntester** 2017-04-03 23:39 UTC

**Comment by DigiAngel** [comment] 2017-04-07 02:20
Ok I found it....you have to select analysis level 4, that's when this happens.  Tried with latest git about 20 minutes ago...thank you.
