### ISSUE TITLE
"?d call" doesn't work

### ISSUE THREAD

**Issue by mrexodia** [hteso/iaito#22] opened 2017-03-30 02:43 UTC
It prints an empty result.

**Comment by trufae** [comment] 2017-03-30 14:07
Works perfectly from r2pipe i guess thats because iaito is not able to find the sdb files for that arch.

**Comment by hteso** [comment] 2017-03-30 15:37
Works in OS X and Linux, could be an issue specific of the Windows build?

**Comment by mrexodia** [comment] 2017-03-30 15:38
I think the reason is that the r2 api doesn't have some environment
variables or something set correctly.

**Comment by mrexodia** [comment] 2017-03-30 23:27
Okay the reason was that r2 uses the current directory to look for the `share` etc folders. I was starting from Qt Creator, which calls `build-blahblah\debug\Iaito.exe` but has the starting directory `build-blahblah\` copying r2 to this directory solved the problem.

**Comment by trufae** [comment] 2017-03-31 08:06
Any proposal to solve that in r2land? Maybe adding an api (or just add an eval var) to change the prefix in runtime?

**Comment by mrexodia** [comment] 2017-03-31 08:50
basically the solution is to check from iaito if the folders are in the right location and just warn the user on startup...

**Comment by trufae** [comment] 2017-03-31 09:08
Why warn the user? Iaito knows where r2 is, and you can just chdir to that dire before corenew() and wverything should work

**Comment by mrexodia** [comment] 2017-03-31 09:09
It might know where r2 is but it doesn't know if the share directory is
there.

**Comment by trufae** [comment] 2017-03-31 09:10
The share directory is in r2 one because its relative

**Comment by trufae** [comment] 2017-03-31 09:11
(On windows builds should be like this, if not thats a regression in our windows builds)

**Comment by hteso** [comment] 2017-03-31 10:29
Fixed with #24

**Closed** 2017-03-31 10:29 UTC
