### ISSUE TITLE
Do not use r2 from PATH

### ISSUE THREAD

**Issue by radare** [hteso/iaito#143] opened 2017-04-19 09:57 UTC
not sure when or why iaito started overriding system PATH env var and trying to use it for something at startup time. iaito uses r2 libraries, he can get ANYTHING at compile or runtime, there's no need to spawn r2 at all. This will not be an issue if PATH wasnt overriden

**Comment by ballessay** [comment] 2017-04-19 20:27
I'm not sure if I understand this fully.
- AFAIK iaito doesn't modify the environment (ok. if a new file is loaded the process gets respawned (with the current process env (if this is a good idea is worth another discussion... pita to debug for sure))).
- I found no place (in master) where r2 is started (qmake uses r2 to get the include und lib paths). Do you refer to the 'r2 -C ...' application output?

**Comment by radare** [comment] 2017-04-20 14:01
> On 19 Apr 2017, at 22:27, C. Balles <notifications@github.com> wrote:
> 
> I'm not sure if I understand this fully.
> 
> AFAIK iaito doesn't modify the environment (ok. if a new file is loaded the process gets respawned (with the current process env (if this is a good idea is worth another discussion... pita to debug for sure))).
the env is modified by qtcreator , its a matter of the project file

> I found no place (in master) where r2 is started (qmake uses r2 to get the include und lib paths). Do you refer to the 'r2 -C ...' application output?

why the hell qmake needs r2 to get this, pkg-config is the tool that is in charge of doing that, not r2

wat? r2 -C is used?

**Comment by XVilka** [comment] 2017-04-20 14:11
There is no pkgconfig on Windows

**Comment by radare** [comment] 2017-04-20 14:13
"pkg-config works on multiple platforms: Linux and other UNIX-like operating systems, Mac OS X and Windows.”

**Comment by ballessay** [comment] 2017-04-20 17:51
Should be fixed with #144. If its confirmed this doesn't break the windows build I'll merge it.

@radare 
> the env is modified by qtcreator , its a matter of the project file

Ok, so its not iaito itself modifing the env. QtCreator has multiple options to modify the environment and needs to do it because of libs not in default paths. By default it will use the env it got started, then in the Kit options and in the project settings (note: *.pro.user not the iaito.pro itself;  I even may forgotten an option). If there is still a problem with the env maybe delete your current iaito.pro.user.

> why the hell qmake needs r2 to get this, pkg-config is the tool that is in charge of doing that, not r2

This solution was propsed in #41 (resp. https://github.com/hteso/iaito/pull/5#issuecomment-290433796) and implemented in #43, where, by the way, even you where fine with it.

> wat? r2 -C is used?

No, it's not. It just shows up in the application output after the background webserver is started (it's a r2(-lib) message not iaito) and i gussed that is where you came to the conclusion that iaito starts r2.

Regarding windows: currently the windows libs are precompiled in a git submodule without a pkgconfig directory. So currently no way I can use pkg-config for that.

**Closed** 2017-04-20 18:17 UTC
